language: erlang
before_install:
  - dialyzer --build_plt --apps erts kernel stdlib compiler crypto
script:
  - autoconf
  - ./configure
  - make depend
  - make
otp_release:
  - 17.4
  - 17.1
  - 17.0
