language: erlang
before_install:
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - python scripts/mk_make.py
  - cd build
  - make
  - sudo make install
  - cd ../..
script:
  - git submodule update
  - git submodule foreach make
  - export ERL_LIBS=$PWD/lib/proper:$ERL_LIBS
  - autoconf
  - ./configure
  - make depend
  - make
  - make dialyzer
otp_release:
  - 17.4
  - 17.0
