language: erlang
before_install:
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - python scripts/mk_make.py
  - cd build
  - make
  - sudo make install
  - cd ..
  - dialyzer --build_plt --apps erts kernel stdlib compiler crypto
script:
  - autoconf
  - ./configure
  - make depend
  - make
otp_release:
  - 17.4
  - 17.0
